//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncomes
    {
        public int IncomeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RoomNo { get; set; }
    
        public virtual tblRooms tblRooms { get; set; }
    }
}
