//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRooms()
        {
            this.tblIncomes = new HashSet<tblIncomes>();
        }
    
        public int RommID { get; set; }
        public Nullable<int> Floor { get; set; }
        public string RoomOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIncomes> tblIncomes { get; set; }
    }
}
